language: node_js
node_js:
  # - "node"
  - "lts/*"
services:
  - docker
install:
  - pushd ./clientapp
  - npm install --no-optional
  - popd
script:
  - pushd ./clientapp
  - npm run build
  - popd
  # TODO: compile azure function from TypeScript
before_deploy:
  - docker build --rm --force-rm -t cicd-deploy -f Dockerfile.deploy .
deploy:
  - provider: script
    skip_cleanup: true
    script: docker run --rm -e TRAVIS -e CICD_AUTH_NAME -e CICD_AUTH_PASSWORD -e CICD_AUTH_TENANT -e FUNCTIONAPP_NAME -v $PWD/scripts:/scripts -v $PWD/functions:/functions -v $PWD/clientapp:/clientapp cicd-deploy bash /scripts/deploy.sh
