sudo: required
language: node_js
node_js:
  # - "node"
  - "lts/*"
python:
  - "3.7"
addons:
  apt:
    packages:
      - wget
      - unzip
      - curl
      - apt-transport-https
install:
  - pushd ./clientapp
  - npm install --no-optional
  - popd
script:
  - pushd ./clientapp
  - npm run build
  - popd
before_deploy:
  # install required tools
  - sudo bash ./scripts/install-azure-cli.sh
  - sudo bash ./scripts/install-func-tools.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/deploy.sh
