# sudo: required
# language: node_js
# node_js:
#   # - "node"
#   - "lts/*"
# python:
#   - "3.7"
services:
  - docker
# addons:
#   apt:
#     packages:
#       - apt-transport-https
#       - curl
#       - lsb-release
#       - unzip
#       - wget
install:
  - echo install
#   - pushd ./clientapp
#   - npm install --no-optional
#   - popd
script:
  - echo script
#   - pushd ./clientapp
#   - npm run build
#   - popd
# before_deploy:
#   # install required tools
#   - sudo bash ./scripts/install-azure-cli.sh
#   - sudo bash ./scripts/install-func-tools.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/travis-deploy.sh
