sudo: required
language: node_js
node_js:
  # - "node"
  - "lts/*"
python:
  - "3.7"
addons:
  apt:
    packages:
      - wget
      - unzip
      - curl
before_install:
  # install azure cli
  - sudo bash ./scripts/install-azure-cli.sh
  - sudo bash ./scripts/install-func-tools.sh
  - |
    az login \
      --service-principal \
      -u "$CICD_AUTH_NAME" \
      -p "$CICD_AUTH_PASSWORD" \
      --tenant "$CICD_AUTH_TENANT"
install:
  - pushd ./clientapp
  - npm install --no-optional
  - popd
script:
  - pushd ./clientapp
  - npm run build
  - popd
deploy:
  - provider: script
    script:
      # deploy function app
      - pushd ./functions
      - func azure functionapp publish --name "$FUNCTIONAPP_NAME"
      - popd
