sudo: required
language: node_js
node_js:
  # - "node"
  - "lts/*"
python:
  - "3.7"
before_install:
  # install azure cli
  - AZ_REPO=$(lsb_release -cs) && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https
  - sudo apt-get update && sudo apt-get install azure-cli
  # - ./scripts/install-azure-cli.sh
  - ./scripts/install-func-tools.sh
  - |
    az login \
      --service-principal \
      -u "$CICD_AUTH_NAME" \
      -p "$CICD_AUTH_PASSWORD" \
      --tenant "$CICD_AUTH_TENANT"
deploy:
  - provider: script
    script:
      # deploy function app
      - pushd ./functions
      - func azure functionapp publish --name "$FUNCTIONAPP_NAME"
      - popd
